# Generated by Django 3.0 on 2021-06-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_description', models.CharField(max_length=250)),
                ('post_fulltext', models.TextField()),
                ('post_author', models.CharField(max_length=50)),
                ('post_create_at', models.DateField()),
            ],
        ),
    ]
