# Generated by Django 3.0 on 2021-06-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_aboutall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aboutall',
        ),
    ]
